language: python
sudo: false
branches:
  only:
    - master
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
  - 3.7
  - 3.8
  - "pypy"
  - "pypy3"
env:
  global:
    - COVERALLS_PARALLEL=true
    - secure: rOe+uZbAk/bSVEUN+/ZxbYPB54LwwJ96gfsMIYK8HnfFMAK6eiBRF9WdPVxZt2XZY+yTnf4HL024hCQ5qVI1Fe0jzo8sukPMZeK2nZO5FPYH4j2IVdzMbtLZ/AP+xeMewa6dVo+6LfUyL45rw/0c6zRiqx96VzRi4G8404hCdohhCmi5UHLR0pjyNkl+t9Hk2+H7lEG/4pMB+hIhRemfkEnhylFX7hmp1v7VRNajMh3L8XCa0B95nhBO5e5s0Sig/92b5zT+/Ho/xdklPS+zo9vGXLKxYRqygmU0M5xRPj8hzE4S/Oj953kfzqdETaOmUsS/VpSHsKMHsTH0gRADpdfFSgLrXFrO2IHP1v237Ue5eVNrkAywEXiHMCjY3Rw4F8LelwsQUd1QGM9NYnzbcCiiiQy6sZuCYeISfz0kKm6BjaooS37ypMWpPtZ334IjV37+/N1zzuhQAozYP4PN+YQpkpumUPOcLcdh9mVdA6Q9rkIl6Kq+S43WBJTRUys240uGzzsH2GYs2oZS5s11k1UHhju2csEFIPTWDWDRtqjeerekgc7+JaBHqpP7Z56/dAWyqV78BZVchCmwnGN5CbPO8eDdzipFqG4bL12wbaciIzOR618SNfmBc2bfjrL/qVAf8UXpkluOCuPvUQTDRs3hGljdrEHQOliAhjcyyXs=
install:
  - pip install -e .
  - pip install coveralls
script:
  - coverage run setup.py test
after_success:
  - coveralls
notifications:
  webhooks: https://coveralls.io/webhook?repo_token=$COVERALLS_REPO_TOKEN
